# Generated by Django 3.1 on 2020-08-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarycore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceType', models.CharField(choices=[('PB', 'Physical copy'), ('EB', 'Ebook'), ('AB', 'Audiobook')], default='PB', max_length=20)),
                ('instanceBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarycore.book')),
            ],
        ),
    ]
