# Generated by Django 3.1 on 2020-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarycore', '0003_auto_20200826_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookDescription',
            field=models.TextField(default='This is a sample description'),
            preserve_default=False,
        ),
    ]
