# Generated by Django 3.1 on 2020-09-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarycore', '0006_bookinstance_borrowedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100)),
                ('authorDescription', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bookAuthor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarycore.author'),
        ),
    ]
