# Generated by Django 3.1 on 2020-10-08 15:31

from django.db import migrations
from django.contrib.auth.models import User, Group

def create_admin(apps, schema_editor):
    group = Group.objects.create(name='library_admins')
    user = User.objects.create_user(username='admin', password='admin')
    user.groups.add(group)
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('librarycore', '0007_auto_20200927_1520'),
    ]

    operations = [
        migrations.RunPython(create_admin)
    ]
