# Generated by Django 3.1 on 2020-10-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarycore', '0010_bookrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrating',
            old_name='ratings',
            new_name='score',
        ),
    ]
